# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

ttitle: Bay Jekyll Theme
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/" # the subpath of the site
url: "https://adrianaschoenhaut.github.io" # the base hostname & protocol for the site
og_image: /assets/img/name_logo_groovy.png
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: adrianaschoenhaut@gmail.com
  follow:
    - type: twitter
      name: Twitter
      link: http://twitter.com/adriana_et_al
      username: "@adriana_et_al"
    - type: facebook
      name: Facebook
      link: http://facebook.com/YourFacebookUsername
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/adriana-schoenhaut-11a3819b/
    - type: github
      name: GitHub
      link: https://github.com/adrianaschoenhaut/

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
